baseURL = 'http://nvxtech.github.io/'
languageCode = 'pt-br'
title = 'NVX tech'
theme = 'nvx'
description = ''
homepage = 'http://nvxtech.github.io/'
tags = []
enableRobotsTxt = true


[menu]
[[menu.main]]
    name = 'Sobre'
    url = '/'
    weight = 1
[[menu.main]]
    name = 'Produtos'
    url = '/#products'
    weight = 3
[[menu.main]]
    name = 'Contato'
    url = '/contact'
    weight = 10